(define-package "binary-parse"
  (0 1)
  ()
  (install-file "load.scm" 'base)
  (install-file "README" 'doc)
  (install-file "NEWS" 'doc)
  (install-string (COPYING) "COPYING" 'doc)
  (install-file "aux.scm" 'scheme)
  (install-file "tiff-prober.scm" 'scheme)
  (install-file "vtiff.scm" 'scheme)
  (install-file "endian.scm" 'scheme)
  (install-file "tiff.scm" 'scheme)
  (install-file "gnu-head-sm.tif" 'misc-shared)
  (install-file "bsp.tiff" 'misc-shared))
