(define-package "sequences"
  (1 0)
  ()
  (install-file "load.scm" 'base)
  (install-file "README" 'doc)
  (install-file "NEWS" 'doc)
  (install-string (COPYING) "COPYING" 'doc)
  (install-file "baseqs.scm" 'scheme)
  (install-file "genseqs.scm" 'scheme)
  (install-file "uniseqs.scm" 'scheme)
  (install-file "composeqs.scm" 'scheme)
  (install-file "specseqs.scm" 'scheme)
  (install-file "vecnames.scm" 'scheme))
