(define-package "dir-streams"
  (0 0)
  ()
  (install-file "load.scm" 'base)
  (install-file "README" 'doc)
  (install-file "NEWS" 'doc)
  (install-string (COPYING) "COPYING" 'doc)
  (install-file "dir-stream.scm" 'scheme)
  (install-file "dir-stream-predicates.scm" 'scheme)
  (install-file "stream.scm" 'scheme))
